[package]
name = "dice"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
regex = "1.6.0"
term_size = "0.3.2"
tokio = { version = "1.19.2", features = ["full"] }
winit = "0.26.1"
